<?php

/**
 * @file
 * Contains varbase_auth.module.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\varbase_auth\Hook\VarbaseAuthHooks;

// Include all helpers.
include_once __DIR__ . '/includes/helpers.inc';

/**
 * Implements hook_preprocess_page().
 */
#[LegacyHook]
function varbase_auth_preprocess_page(&$variables) {
  \Drupal::service(VarbaseAuthHooks::class)->preprocessPage($variables);
}
